### ISSUE TITLE
ID:730611309(10362)game Oun Moji

### ISSUE THREAD

**Issue by smalldee94** [NerveCheats/ML-Scrapper#1]
![image](https://user-images.githubusercontent.com/127261558/223978442-b4a63da5-28ec-44b8-9ea5-423370862928.png)

**Comment by lutfilahdzaky** [comment]
@smalldee94 Hah?

**Comment by smalldee94** [comment]
![Uploading 7C14E4AD-09C4-4075-90E9-0307FB867116.png…]id-703611309(10362)
